### ISSUE TITLE
matcher type conflict with a class instance method parameters type

### ISSUE THREAD

**Issue by diogonlucena** [NiGhTTraX/strong-mock#326]
First of all: Loved your lib
Im testing it here on a project and will probably use it

Not sure I've missed something but I've seen examples on how to mock an interface and function.
Testing them I can see that there's no typing problem with the matcher but when I create a mock from a Class and want to apply a matcher to a specific method, I need to cast the matcher as the method input

eg:
```
const secretsClient = mock<SecretsManagerClient>();
const expectedSecretOutput = ...

when(() =>
      secretsClient.send(It.matches((command) => command.input.SecretId === "secretKey") as GetSecretValueCommand)
    ).thenResolve(expectedSecretOutput);
```

If I remove the "as GetSecretValueCommand" part, typescript will complain: 
```
TS2345: Argument of type 'Matcher' is not assignable to parameter of type 
'Command<
  ServiceInputTypes, 
  ServiceInputTypes, 
  ServiceOutputTypes, 
  ServiceOutputTypes, 
  SmithyResolvedConfiguration<HttpHandlerOptions>
>'.

Type 'Matcher' is missing the following properties from type 
'Command<
  ServiceInputTypes, 
  ServiceInputTypes, 
  ServiceOutputTypes, 
  ServiceOutputTypes, 
  SmithyResolvedConfiguration<HttpHandlerOptions>
>'.:
input, middlewareStack, resolveMiddleware
```

Im not sure if this is actually a problem with the current implementation of SecretsManagerClient (@aws-sdk/client-secrets-manager)

thanks ^^

**Comment by NiGhTTraX** [comment]
Hey @diogonlucena, `SecretsManagerClient.send` uses a generic type parameter for the input. Matchers are generic too, so when TypeScript compares them and tries to pick a type for the argument inside `It.matches` it chooses `unknown` because there's no other information coming from `client.send`.

You either have to type assert the matcher like you did in the example above, or instantiate the generic(s) for `send`:

```ts
when(() => secretsClient.send<{ SecretId: string }, ...>(
  It.matches((command) => ...)
  //            ^? { input: { SecretId: string } }
)).thenResolve(...);
```

That being said, I would suggest not mocking `@aws-sdk` directly, but instead creating an interface that abstracts those 3rd party types and provides simpler domain types:

```ts
// Your domain type, easy to work with, easy to mock.
type SecretThingy = {
  send: (secret: string) => ...
}

// This is the bridge between your domain types and the AWS types.
const awsSecretThingy: SecretThingy = {
  send: (secret) => secretsClient.send({ SecretId: secret })
}
```

**Comment by diogonlucena** [comment]
thanks a lot
this class is already a wrapping for the manager client with a simple cache

the idea of the type is nice but It seems that it will require udpates everytime I need a new method usage

thanks ^^
